<?php

namespace cc\BatiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisanRepository extends EntityRepository
{
    
    public function chercherArtisan($login, $mdp){
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.login = :login')
                ->setParameter('login', $login)
                ->andWhere('a.mdp = :mdp')
                ->setParameter('mdp', $mdp);
                
        return $qb->getQuery()->getOneOrNullResult();
    }
    
}
