<?php

namespace cc\BatiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisanRepository extends EntityRepository
{
}
