<?php

namespace cc\BatiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChefChantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefChantierRepository extends EntityRepository
{
    
    public function chercherChef($login, $mdp){
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.login = :login')
                ->setParameter('login', $login)
                ->andWhere('c.mdp = :mdp')
                ->setParameter('mdp', $mdp);
                
        return $qb->getQuery()->getOneOrNullResult();
    }
    
}
