<?php

namespace cc\BatiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepreneurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepreneurRepository extends EntityRepository
{
    
    public function chercherEntrepreneur($login, $mdp){
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.login = :login')
                ->setParameter('login', $login)
                ->andWhere('e.mdp = :mdp')
                ->setParameter('mdp', $mdp);
                
        return $qb->getQuery()->getOneOrNullResult();
    }
    
}
