<?php

namespace cc\BatiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionnaireRepository extends EntityRepository
{
    
    public function chercherGestionnaire($login, $mdp){
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.login = :login')
                ->setParameter('login', $login)
                ->andWhere('g.mdp = :mdp')
                ->setParameter('mdp', $mdp);
                
        return $qb->getQuery()->getOneOrNullResult();
    }
    
}
